In [14]:
from qiskit.algorithms.optimizers import GradientDescent
import numpy as np

def f(x):
    print (x, np.linalg.norm(x))
    return (np.linalg.norm(x) - 1) ** 2

initial_point = np.array([1, 0.5, -0.2])

optimizer = GradientDescent(maxiter=500)

result = optimizer.minimize(fun=f, x0=initial_point)

print(f"Found minimum {result.x} at a value"
    "of {result.fun} using {result.nfev} evaluations.")

[ 1.   0.5 -0.2] 1.1357816691600546
[ 1.01  0.5  -0.2 ] 1.1445959985951375
[ 1.    0.51 -0.2 ] 1.1402192771568107
[ 1.    0.5  -0.19] 1.134063490286148
[ 0.99752866  0.49877522 -0.19953636] 1.1329849511003882
[ 1.00752866  0.49877522 -0.19953636] 1.1417992260451715
[ 0.99752866  0.50877522 -0.19953636] 1.137422702314236
[ 0.99752866  0.49877522 -0.18953636] 1.1312666229784174
[ 0.99510664  0.49757521 -0.19908229] 1.130244250947618
[ 1.00510664  0.49757521 -0.19908229] 1.1390584706290492
[ 0.99510664  0.50757521 -0.19908229] 1.134682145396749
[ 0.99510664  0.49757521 -0.18908229] 1.1285257733270457
[ 0.99273294  0.4963995  -0.1986376 ] 1.1275584470895246
[ 1.00273294  0.4963995  -0.1986376 ] 1.1363726107433296
[ 0.99273294  0.5063995  -0.1986376 ] 1.1319964847901656
[ 0.99273294  0.4963995  -0.1886376 ] 1.1258398197239765
[ 0.99040661  0.49524758 -0.1982021 ] 1.1249264403586299
[ 1.00040661  0.49524758 -0.1982021 ] 1.1337405472293332
[ 0.99040661  0.50524758 -0.1982021 ] 1.1293646213251