In [8]:
from qiskit.algorithms.optimizers import GradientDescent
import numpy as np

def f(x):
    print (x, np.linalg.norm(x))
    return (np.linalg.norm(x) - 1) ** 2

initial_point = np.array([1, 0.5, -0.2])

optimizer = GradientDescent(maxiter=100)

result = optimizer.minimize(fun=f, x0=initial_point)

print(f"Found minimum {result.x} at a value"
    "of {result.fun} using {result.nfev} evaluations.")

[ 1.   0.5 -0.2]
[ 1.01  0.5  -0.2 ]
[ 1.    0.51 -0.2 ]
[ 1.    0.5  -0.19]
[ 0.99752866  0.49877522 -0.19953636]
[ 1.00752866  0.49877522 -0.19953636]
[ 0.99752866  0.50877522 -0.19953636]
[ 0.99752866  0.49877522 -0.18953636]
[ 0.99510664  0.49757521 -0.19908229]
[ 1.00510664  0.49757521 -0.19908229]
[ 0.99510664  0.50757521 -0.19908229]
[ 0.99510664  0.49757521 -0.18908229]
[ 0.99273294  0.4963995  -0.1986376 ]
[ 1.00273294  0.4963995  -0.1986376 ]
[ 0.99273294  0.5063995  -0.1986376 ]
[ 0.99273294  0.4963995  -0.1886376 ]
[ 0.99040661  0.49524758 -0.1982021 ]
[ 1.00040661  0.49524758 -0.1982021 ]
[ 0.99040661  0.50524758 -0.1982021 ]
[ 0.99040661  0.49524758 -0.1882021 ]
[ 0.98812669  0.49411899 -0.19777561]
[ 0.99812669  0.49411899 -0.19777561]
[ 0.98812669  0.50411899 -0.19777561]
[ 0.98812669  0.49411899 -0.18777561]
[ 0.98589226  0.49301326 -0.19735795]
[ 0.99589226  0.49301326 -0.19735795]
[ 0.98589226  0.50301326 -0.19735795]
[ 0.98589226  0.49301326 -0.18735795]
[ 0.9837023

In [9]:
from qiskit.algorithms.optimizers import GradientDescent

def learning_rate():
    power = 0.6
    constant_coeff = 0.1
    def powerlaw():
        n = 0
        while True:
            yield constant_coeff * (n ** power)
            n += 1

    return powerlaw()

def f(x):
    return (np.linalg.norm(x) - 1) ** 2

def grad_f(x):
    return 2 * (np.linalg.norm(x) - 1) * x / np.linalg.norm(x)

initial_point = np.array([1, 0.5, -0.2])

optimizer = GradientDescent(maxiter=100, learning_rate=learning_rate)
result = optimizer.minimize(fun=f, jac= , x0=initial_point)

print(f"Found minimum {result.x} at a value"
"of {result.fun} using {result.nfev} evaluations.", result.nfev, result.fun)

SyntaxError: invalid syntax (3419525608.py, line 23)